{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "tests-app/api-docs",
    "description": "Showing api-docs",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [{ "url": "http://localhost:3001" }],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Google Auth",
      "description": "GoogleAuth endpoints"
    },
    {
      "name": "User",
      "description": "User endpoints"
    },

    {
      "name": "Tests",
      "description": "Tests endpoints"
    }
  ],
  "paths": {
    "/api/users/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Conflict",
            "content": {}
          }
        }
      }
    },
    "/api/users/verify/:verifyToken": {
      "get": {
        "tags": ["Auth"],
        "summary": "User verification",
        "parameters": [
          {
            "in": "path",
            "name": "verifyToken",
            "required": true,
            "type": "string",
            "description": "User's verify email with his verifyToken"
          }
        ],
        "responses": {
          "200": {
            "description": "Verification successful",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponceVerificationSuccess"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/api/users/verify": {
      "post": {
        "tags": ["Auth"],
        "summary": "Send again user verification",
        "parameters": [],
        "requestBody": {
          "description": "User email",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestVerify"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponceVerify"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/api/users/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authontication",
        "parameters": [],
        "requestBody": {
          "description": "Authorisation's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthonticationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Email already exists",
            "content": {}
          }
        }
      }
    },
    "/api/users/signout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout",
        "parameters": [
          {
            "in": "headers",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SignOutResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/api/users/current": {
      "post": {
        "tags": ["User"],
        "summary": "Get current user",
        "parameters": [
          {
            "in": "headers",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentUserResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/api/users/google": {
      "get": {
        "tags": ["Google Auth"],
        "summary": "Google user registration",
        "parameters": [],
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GoogleAuthResponse"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          }
        }
      }
    },
    "/api/tests/qa-practices": {
      "get": {
        "tags": ["Tests"],
        "summary": "QA practices tests",
        "parameters": [
          {
            "in": "headers",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "responses": {
          "200": {
            "descriotion": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestsResponce"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["Tests"],
        "summary": "QA practice tests result",
        "parameters": [
          {
            "in": "headers",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "responses": {
          "200": {
            "descriotion": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestsResultResponce"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    },
    "/api/tests/qa-theories": {
      "get": {
        "tags": ["Tests"],
        "summary": "QA theory tests",
        "parameters": [
          {
            "in": "headers",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "responses": {
          "200": {
            "descriotion": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestsResponce"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      },
      "post": {
        "tags": ["Tests"],
        "summary": "QA theories tests result",
        "parameters": [
          {
            "in": "path",
            "name": "Authorization",
            "required": true,
            "type": "string",
            "description": "Token of current user"
          }
        ],
        "responses": {
          "200": {
            "descriotion": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestsResultResponce"
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {}
          },
          "400": {
            "description": "Bad request",
            "content": {}
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "minLength": 6
          }
        },
        "example": {
          "email": "example@gmail.com",
          "password": "qwerty"
        }
      },
      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "user": {
              "type": "object",
              "email": {
                "type": "string",
                "format": "email"
              },
              "verify": {
                "type": "boolean"
              },
              "verifyToken": {
                "type": "string"
              },
              "googleAuth": {
                "type": "boolean"
              },
              "password": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 201,
          "data": {
            "user": {
              "email": "example@gmail.com",
              "verify": false,
              "verifyToken": "qwer_qwee_aaaa",
              "googleAuth": false,
              "password": "$2a$06$ecoVYU6VRflaasdalhKQL3.bqd9dzaO7fkyqqN0PBwq4Yc1j8LC9MO"
            }
          }
        }
      },
      "AuthonticationResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "user": {
              "type": "object",
              "email": {
                "type": "string",
                "format": "email"
              },
              "verify": {
                "type": "boolean"
              },
              "verifyToken": {
                "type": "string"
              },
              "googleAuth": {
                "type": "boolean"
              },
              "password": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "user": {
              "email": "example@gmail.com",
              "verify": true,
              "verifyToken": null,
              "googleAuth": false,
              "password": "$2a$06$ecoVYU6VRflaasdalhKQL3.bqd9dzaO7fkyqqN0PBwq4Yc1j8LC9MO"
            }
          }
        }
      },
      "ResponceVerificationSuccess": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "message": "Verification successful"
        }
      },
      "RequestVerify": {
        "type": "object",
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          }
        },
        "example": {
          "email": "example@gmail.com"
        }
      },
      "ResponceVerify": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "message": {
            "type": "string"
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "message": "Verification email sent"
        }
      },
      "SignOutResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          }
        },
        "example": {
          "status": "success",
          "code": 204
        }
      },
      "CurrentUserResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "user": {
              "type": "object",
              "email": {
                "type": "string"
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "user": {
              " email": "example@gmail.com"
            }
          }
        }
      },
      "GoogleAuthResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "user": {
              "type": "object",
              "email": {
                "type": "string",
                "format": "email"
              },
              "verify": {
                "type": "boolean"
              },
              "verifyToken": {
                "type": "string"
              },
              "googleAuth": {
                "type": "boolean"
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 201,
          "data": {
            "user": {
              "email": "example@gmail.com",
              "verify": false,
              "verifyToken": "qwer_qwee_aaaa",
              "googleAuth": true
            }
          }
        }
      },
      "TestsResponce": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "result": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "_id": {
                    "type": "string"
                  },
                  "question": {
                    "type": "string"
                  },
                  "answers": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "rightAnswer": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "result": [
              {
                "_id": "123465768706",
                "question": "Example",
                "answers": ["a", "b", "c", "d"],
                "rightAnswer": "a"
              }
            ]
          }
        }
      },
      "TestsResultResponce": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object",
            "feedback": {
              "type": "string"
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "feedback": "75%"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
